version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: empresa_internet
    restart: always
    environment:
      - MYSQL_DATABASE=empresa_internet
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - ./my-volumes/empresa.sql:/docker-entrypoint-initdb.d/empresa.sql
      - db-data:/var/lib/mysql
volumes:
  db-data:
