version: '3.8'
services:
  db:
    image: mysql:8
    container_name: movies_adv
    restart: always
    environment:
      - MYSQL_DATABASE=movies_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - ./my-volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my-config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - db-data:/var/lib/mysql
volumes:
  db-data:
